[project]
name = "reconstructing-bluesky"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ujson>=5.10.0",
]

[tool.uv.sources]
src = { path = './src' }
